import {MeshTxBuilder} from '@meshsdk/core'
import {
  addRefScriptCarrier,
  type Contract,
  ensure,
  generateConstantContracts,
  type RefScriptCarrierDatum,
  SUNDAE_POOL_SCRIPT_HASH,
  WR_POOL_SYMBOL,
  WR_POOL_VALIDATOR_HASH,
} from '@wingriders/multi-dex-launchpad-common'
import {Command} from 'commander'
import {
  offlineEvaluator,
  ogmiosProvider,
  updateFetcherFromOgmios,
} from '../agent/providers'
import {getWallet, getWalletPubKeyHash, initWallet} from '../agent/wallet'
import {config} from '../config'
import {logger} from '../logger'

const FOLDER_NAME = '../common/src/ref-scripts'

export const buildDeployConstantContractsCommand = () => {
  const command = new Command('deploy-constant-contracts')

  command
    .description(
      'Build and submit a transaction that creates UTxOs with reference scripts for constant launchpad contracts',
    )
    .action(async () => {
      logger.info('Initializing wallet...')
      await initWallet()
      const wallet = getWallet()
      await updateFetcherFromOgmios()
      const changeAddress = await wallet.getChangeAddress()
      const walletUtxos = await wallet.getUtxos()

      logger.info('Generating constant contracts...')
      const constantContracts = await generateConstantContracts({
        sundaePoolScriptHash: SUNDAE_POOL_SCRIPT_HASH[config.NETWORK],
        wrPoolSymbol: WR_POOL_SYMBOL[config.NETWORK],
        wrPoolValidatorHash: WR_POOL_VALIDATOR_HASH[config.NETWORK],
      })

      logger.info('Building and submitting transaction...')
      const b = new MeshTxBuilder({
        submitter: ogmiosProvider,
        evaluator: offlineEvaluator,
      })
        .setNetwork(config.NETWORK)
        .changeAddress(changeAddress)
        .selectUtxosFrom(walletUtxos)

      const datum: RefScriptCarrierDatum = {
        ownerPubKeyHash: getWalletPubKeyHash(),
        // Since the owner is the agent, any deadline is fine
        deadline: 0,
      }

      const contractsToDeploy: {name: string; contract: Contract}[] = [
        {
          name: 'failProofPolicy',
          contract: constantContracts.failProofPolicy,
        },
        {
          name: 'failProofValidator',
          contract: constantContracts.failProofValidator,
        },
        {
          name: 'poolProofPolicy',
          contract: constantContracts.poolProofPolicy,
        },
        {
          name: 'poolProofValidator',
          contract: constantContracts.poolProofValidator,
        },
        {
          name: 'rewardsHolderValidator',
          contract: constantContracts.rewardsHolderValidator,
        },
      ]

      for (const {contract} of contractsToDeploy)
        addRefScriptCarrier(b, config.NETWORK, datum, contract)

      const builtTx = await b.complete()
      logger.info('Transaction built successfully')

      const signedTx = await wallet.signTx(builtTx)
      logger.info('Transaction signed successfully')

      const txHash = await wallet.submitTx(signedTx)
      logger.info(`Transaction submitted successfully: ${txHash}`)

      const buildUtxoContent = (
        name: string,
        outputIndex: number,
        scriptHash: string,
      ): string => {
        const output = b.meshTxBuilderBody.outputs[outputIndex]

        ensure(output != null, {outputIndex}, 'Output not found')
        ensure(
          output.referenceScript != null,
          {output},
          'Output must have a reference script',
        )

        return `${name}: {
            input: {txHash: '${txHash}', outputIndex: ${outputIndex}},
            output: {address: '${output.address}', amount: [${output.amount.map(({unit, quantity}) => `{unit: '${unit}', quantity: '${quantity}'}`).join(', ')}], scriptRef: '8202${output.referenceScript.code}', scriptHash: '${scriptHash}'},
            scriptSize: ${output.referenceScript.code.length / 2},
          },`
      }

      const fileContent = [
        '// IMPORTANT: This file is automatically generated by deploy-constant-contracts script, do not edit it manually',
        'import { RefSCriptUTxO } from "../types"',
        '',
        `export const ${config.NETWORK}ConstantContracts = {`,
        ...contractsToDeploy.map(({name, contract}, index) =>
          buildUtxoContent(name, index, contract.hash),
        ),
        '} satisfies Record<string, RefSCriptUTxO>',
      ].join('\n')

      const filename = `${FOLDER_NAME}/${config.NETWORK}.ts`
      await Bun.write(filename, fileContent)
      logger.info(`Reference scripts written to ${filename}`)

      // format the file
      await new Promise((resolve, _) => {
        Bun.spawn(['biome', 'check', filename, '--write'], {
          onExit(proc, exitCode, signalCode, error) {
            if (error != null) {
              logger.error(
                {stderr: proc.stderr, exitCode, signalCode},
                `Biome exited with error ${error.message}`,
              )
              resolve(exitCode ?? 1)
            } else {
              resolve(0)
            }
          },
        })
      })
    })

  return command
}
